# Generated by Django 4.2 on 2025-07-26 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_suggestions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
