# Generated by Django 4.2 on 2025-07-28 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_friends_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends_suggestions',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
